In [264]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, IsolationForest 
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from keras.models import Sequential, Model
from keras.layers import Dense, LSTM, Conv2D, Dropout, MaxPool2D, Flatten
from sklearn.metrics import mean_absolute_error
# import xgboost as xgb
train = pd.read_csv('train.csv', index_col=0)
test = pd.read_csv('test.csv', index_col=0)
submission = pd.read_csv('sample_submission.csv', index_col=0)

train = train.interpolate()
test = test.interpolate()

train = train.fillna(train.mean())
test = test.fillna(train.mean())

print(train.shape)
print(test.shape)

train = np.array(train)
x_predict = np.array(test)

x = train[:,:71]
y = train[:,71:]

# 전처리
from sklearn.preprocessing import RobustScaler, StandardScaler
scaler = RobustScaler()
scaler.fit(x) 
x = scaler.transform(x)
x_predict = scaler.transform(x_predict)

# from sklearn.decomposition import PCA
# pca = PCA(n_components=12)
# pca.fit(x)
# x = pca.transform(x)
# x_predict = pca.transform(x_predict)

# from sklearn.decomposition import PCA
# pca = PCA(n_components=20)
# pca.fit(x)
# x = pca.transform(x) 

(10000, 75)
(10000, 71)


In [167]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x) 
x = scaler.transform(x)
x_predict = scaler.transform(x_predict)

In [265]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=43)

# model = Sequential()
# model.add(Dense(52, input_dim=(71))) 
# model.add(Dense(228))
# model.add(Dense(356))
# model.add(Dropout(0.2))
# model.add(Dense(250))
# model.add(Dense(164))
# model.add(Dropout(0.4))
# model.add(Dense(64))
# model.add(Dense(4, activation='relu')) 
# model.summary()

# from sklearn.metrics import mean_absolute_error

# model.compile(loss='mae', optimizer='adam', metrics=['mae']) 
# model.fit(x_train,y_train, epochs=500, batch_size=50)
# y_pred = model.predict(x_test)
# mse = mean_absolute_error(y_pred, y_test)
# print(mse)

model = RandomForestRegressor()
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

# model = xgb()
# model.fit(x_train,y_train)
# y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
# mae = mean_absolute_error(y_pred, y_test)
# print('xgboost mae 는', mae)

C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


랜덤포레스트 mae 는 1.5301087499999988


In [266]:
x_train, x_test, y_train, y_test = train_test_split(x1,y, test_size=0.2, random_state=43)

# model = Sequential()
# model.add(Dense(52, input_dim=(71))) 
# model.add(Dense(228))
# model.add(Dense(356))
# model.add(Dropout(0.2))
# model.add(Dense(250))
# model.add(Dense(164))
# model.add(Dropout(0.4))
# model.add(Dense(64))
# model.add(Dense(4, activation='relu')) 
# model.summary()

# from sklearn.metrics import mean_absolute_error

# model.compile(loss='mae', optimizer='adam', metrics=['mae']) 
# model.fit(x_train,y_train, epochs=500, batch_size=50)
# y_pred = model.predict(x_test)
# mse = mean_absolute_error(y_pred, y_test)
# print(mse)

model1 = RandomForestRegressor()
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

# model = xgb()
# model.fit(x_train,y_train)
# y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
# mae = mean_absolute_error(y_pred, y_test)
# print('xgboost mae 는', mae)

C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


랜덤포레스트 mae 는 1.5323772499999995


In [251]:
pred = model1.predict(x_predict1)

In [ ]:
pred = model1.predict(x_predict1)
submission = pd.read_csv('sample_submission.csv', index_col=0)
submission['hhb'] = pred[:,0]
submission['hbo2'] = pred[:,1]
submission['ca'] = pred[:,2]
submission['na'] = pred[:,3]

In [252]:
submission = pd.read_csv('sample_submission.csv', index_col=0)

In [239]:
submission.columns

Index(['hhb', 'hbo2', 'ca', 'na'], dtype='object')

In [240]:
submission.shape

(10000, 4)

In [253]:
pred[:,0]

array([ 7.33 ,  6.53 , 11.439, ...,  9.724,  9.455,  6.11 ])

In [255]:
submission

hhb   hbo2      ca     na
id                                 
10000   7.330  3.861   7.608  2.890
10001   6.530  3.993   6.310  2.105
10002  11.439  4.057   9.335  3.524
10003   8.239  4.599   9.715  3.084
10004   8.279  3.615   9.837  4.130
...       ...    ...     ...    ...
19995   6.134  4.480   9.480  3.342
19996   7.258  4.027   9.550  3.275
19997   9.724  3.333   9.786  3.206
19998   9.455  4.714  11.051  2.773
19999   6.110  4.011   9.873  3.264

[10000 rows x 4 columns]

In [257]:
submission.to_csv('submission1_1.csv')

In [256]:
submission.to_csv('submission1.csv', index=None)

In [248]:
pred = pd.DataFrame(pred,index = None )

In [247]:
pred

0      1       2      3
0      7.330  3.861   7.608  2.890
1      6.530  3.993   6.310  2.105
2     11.439  4.057   9.335  3.524
3      8.239  4.599   9.715  3.084
4      8.279  3.615   9.837  4.130
...      ...    ...     ...    ...
9995   6.134  4.480   9.480  3.342
9996   7.258  4.027   9.550  3.275
9997   9.724  3.333   9.786  3.206
9998   9.455  4.714  11.051  2.773
9999   6.110  4.011   9.873  3.264

[10000 rows x 4 columns]

In [249]:
pd.concat([submission,pred])

0      1       2      3   ca  hbo2  hhb   na
10000    NaN    NaN     NaN    NaN  0.0   0.0  0.0  0.0
10001    NaN    NaN     NaN    NaN  0.0   0.0  0.0  0.0
10002    NaN    NaN     NaN    NaN  0.0   0.0  0.0  0.0
10003    NaN    NaN     NaN    NaN  0.0   0.0  0.0  0.0
10004    NaN    NaN     NaN    NaN  0.0   0.0  0.0  0.0
...      ...    ...     ...    ...  ...   ...  ...  ...
9995   6.134  4.480   9.480  3.342  NaN   NaN  NaN  NaN
9996   7.258  4.027   9.550  3.275  NaN   NaN  NaN  NaN
9997   9.724  3.333   9.786  3.206  NaN   NaN  NaN  NaN
9998   9.455  4.714  11.051  2.773  NaN   NaN  NaN  NaN
9999   6.110  4.011   9.873  3.264  NaN   NaN  NaN  NaN

[20000 rows x 8 columns]

In [237]:
pred.shape

(10000, 4)

In [287]:
y_pred.shape

(2000, 4)

In [286]:
y_test

array([[11.84,  3.62,  8.4 ,  3.67],
       [ 9.85,  5.45, 10.04,  6.6 ],
       [ 9.24,  5.39,  9.8 ,  2.68],
       ...,
       [10.47,  2.01, 10.18,  0.59],
       [ 4.97,  4.62, 12.76,  5.19],
       [ 4.42,  6.97,  7.92,  3.79]])

In [299]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=43)

model2 = RandomForestRegressor()
model2.fit(x_train,y_train)
y_pred = model2.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)


C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


랜덤포레스트 mae 는 1.5421246249999998


In [301]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=43)

model = RandomForestRegressor(n_estimators=500)
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

랜덤포레스트 mae 는 1.4532793649999995


In [306]:
pred = model.predict(x_predict)

In [307]:
submission['hhb'] = pred[:,0]
submission['hbo2'] = pred[:,1]
submission['ca'] = pred[:,2]
submission['na'] = pred[:,3]
submission.to_csv('submission3.csv')

In [310]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=43)

model1 = RandomForestRegressor(n_estimators=150, criterion='mae',max_features = "auto", min_samples_leaf = 50)
model1.fit(x_train,y_train)
y_pred = model1.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

랜덤포레스트 mae 는 1.5728161916666672


In [ ]:
# 요기!

In [ ]:
pred = model1.predict(x_predict1)

In [269]:
from sklearn.ensemble import BaggingRegressor

In [270]:
model = BaggingRegressor()
model.fit(x_train,y_train)
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

랜덤포레스트 mae 는 1.5366874166666697


In [289]:
from xgboost import XGBRegressor

In [290]:
model = XGBRegressor()

In [298]:
model.fit(x_train,y_train)

ValueError: ('Expecting 2 dimensional numpy.ndarray, got: ', (568000,))

In [292]:
y_pred = model.predict(x_test) # 회귀던 분류던 사용할 수 있음

In [293]:
y_pred.shape

(2000,)

In [282]:
mae = mean_absolute_error(y_pred, y_test)
print('랜덤포레스트 mae 는', mae)

ValueError: y_true and y_pred have different number of output (1!=4)

In [262]:
y_test

array([[11.84,  3.62,  8.4 ,  3.67],
       [ 9.85,  5.45, 10.04,  6.6 ],
       [ 9.24,  5.39,  9.8 ,  2.68],
       ...,
       [ 3.79,  4.38, 12.41,  6.65],
       [10.06,  2.48, 13.2 ,  0.54],
       [ 6.66,  3.64,  8.38,  5.05]])

In [263]:
y_pred

array([6.16321  , 6.320355 , 6.024196 , ..., 6.0358505, 6.09962  ,
       6.1918197], dtype=float32)